import Navbar from "@/components/navbar/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hello",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
  <main>
    <Navbar/>
    {children}
  </main>
  );
}
